require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'

task :default => :test

desc "run tests"
task :test do
  # just run tests, nothing fancy
  Dir["test/**/*.rb"].sort.each { |test|  load test }
end
