source 'https://rubygems.org'
gem 'rake'
gem 'sinatra'
gem 'json'
gem 'rack-flash3'
#gem 'rack-ssl-enforcer'

group :development, :test do
   gem 'rack-test'
   gem 'mocha'
end

group :development do
  gem 'shotgun'
  gem 'pry'
  gem 'leader', :git => 'git://github.com/halo/leader.git'
  gem 'foreman'
  gem "better_errors"
  gem "binding_of_caller"
end
